### ISSUE TITLE
resize bar

### ISSUE THREAD

**Issue by sakgoyal** [LuckFire/BottomBar#3]
is there a way to resize the bar? I feel that it is way too tall for my small screen. it also adds a bar onto the friends list which I do not like since it makes the viewable area smaller. is there a way to add a toggle to enable/disable the bar in the friend area and a way to edit the height of the bottom bar so I can make it thinner?

**Comment by LuckFire** [comment]
as of v1.4.0, yes you are

please redownload the theme and check out the latest changelog for more info
